notify-update: true
# which world is it allowed to claim in
worlds:
  - world
  - world_nether
  - world_the_end
  - test
economy:
  cost: 1000.0
  refund: 750.0
  # each claim adds %25 of the cost
  # first claim $cost
  # second claim $cost + %multiply of cost
  # its best to test it out before using it public
  multiply: 25
max-claims:
  default: 32
  vip: 36
  staff: 64
  op: 9999
claim:
  manipulate-fly: false
  expires: 31
  particle:
    type: TOTEM_OF_UNDYING
    spread: 4
    height: 6
    amount: 75
  sound:
    type: BLOCK_AMETHYST_BLOCK_BREAK
    volume: 0.75
    pitch: 1.0
unclaim:
  particle:
    type: SPELL_INSTANT
    spread: 4
    height: 6
    amount: 75
  sound:
    type: BLOCK_AMETHYST_BLOCK_BREAK
    volume: 0.75
    pitch: 1.0
pvp-inside-claims: true
redstone-only-in-claims: false
disable-block-break: true
disable-block-fertilize: true
disable-block-place: true
disable-cauldron-level-change: true
disable-tnt-block-damage: true
disable-sign-change: true
disable-fluid-from-outside: true
disable-piston-from-outside: true
disable-physical-blocks:
  ACACIA_PRESSURE_PLATE: true
  BAMBOO_PRESSURE_PLATE: true
  BIRCH_PRESSURE_PLATE: true
  CHERRY_PRESSURE_PLATE: true
  CRIMSON_PRESSURE_PLATE: true
  DARK_OAK_PRESSURE_PLATE: true
  FARMLAND: true
  HEAVY_WEIGHTED_PRESSURE_PLATE: true
  JUNGLE_PRESSURE_PLATE: true
  LIGHT_WEIGHTED_PRESSURE_PLATE: true
  MANGROVE_PRESSURE_PLATE: true
  OAK_PRESSURE_PLATE: true
  POLISHED_BLACKSTONE_PRESSURE_PLATE: true
  SNIFFER_EGG: true
  SPRUCE_PRESSURE_PLATE: true
  STONE_PRESSURE_PLATE: true
  TURTLE_EGG: true
  WARPED_PRESSURE_PLATE: true
disable-interact-blocks:
  ACACIA_BUTTON: true
  ACACIA_DOOR: true
  ACACIA_FENCE_GATE: true
  ACACIA_TRAPDOOR: true
  ANVIL: true
  BAMBOO_BUTTON: true
  BAMBOO_DOOR: true
  BAMBOO_FENCE_GATE: true
  BAMBOO_TRAPDOOR: true
  BARREL: true
  BEACON: true
  BELL: true
  BIRCH_BUTTON: true
  BIRCH_DOOR: true
  BIRCH_FENCE_GATE: true
  BIRCH_TRAPDOOR: true
  BLACK_CANDLE: true
  BLACK_SHULKER_BOX: true
  BLUE_CANDLE: true
  BLUE_SHULKER_BOX: true
  BREWING_STAND: true
  BROWN_CANDLE: true
  BROWN_SHULKER_BOX: true
  CANDLE: true
  CHERRY_BUTTON: true
  CHERRY_DOOR: true
  CHERRY_FENCE_GATE: true
  CHERRY_TRAPDOOR: true
  CHEST: true
  CHIPPED_ANVIL: true
  CHISELED_BOOKSHELF: true
  COMPARATOR: true
  COPPER_DOOR: true
  COPPER_TRAPDOOR: true
  CRAFTER: true
  CRIMSON_BUTTON: true
  CRIMSON_DOOR: true
  CRIMSON_FENCE_GATE: true
  CRIMSON_TRAPDOOR: true
  CYAN_CANDLE: true
  CYAN_SHULKER_BOX: true
  DAMAGED_ANVIL: true
  DARK_OAK_BUTTON: true
  DARK_OAK_DOOR: true
  DARK_OAK_FENCE_GATE: true
  DARK_OAK_TRAPDOOR: true
  DAYLIGHT_DETECTOR: true
  DECORATED_POT: true
  DISPENSER: true
  DROPPER: true
  EXPOSED_COPPER_DOOR: true
  EXPOSED_COPPER_TRAPDOOR: true
  FLOWER_POT: true
  GRAY_CANDLE: true
  GRAY_SHULKER_BOX: true
  GREEN_CANDLE: true
  GREEN_SHULKER_BOX: true
  HOPPER: true
  JUKEBOX: true
  JUNGLE_BUTTON: true
  JUNGLE_DOOR: true
  JUNGLE_FENCE_GATE: true
  JUNGLE_TRAPDOOR: true
  LECTERN: true
  LEVER: true
  LIGHT_BLUE_CANDLE: true
  LIGHT_BLUE_SHULKER_BOX: true
  LIGHT_GRAY_CANDLE: true
  LIGHT_GRAY_SHULKER_BOX: true
  LIME_CANDLE: true
  LIME_SHULKER_BOX: true
  MAGENTA_CANDLE: true
  MAGENTA_SHULKER_BOX: true
  MANGROVE_BUTTON: true
  MANGROVE_DOOR: true
  MANGROVE_FENCE_GATE: true
  MANGROVE_TRAPDOOR: true
  OAK_BUTTON: true
  OAK_DOOR: true
  OAK_FENCE_GATE: true
  OAK_TRAPDOOR: true
  ORANGE_CANDLE: true
  ORANGE_SHULKER_BOX: true
  OXIDIZED_COPPER_DOOR: true
  OXIDIZED_COPPER_TRAPDOOR: true
  PING_SHULKER_BOX: true
  PINK_CANDLE: true
  POLISHED_BLACKSTONE_BUTTON: true
  PURPLE_CANDLE: true
  PURPLE_SHULKER_BOX: true
  RED_CANDLE: true
  RED_SHULKER_BOX: true
  REDSTONE_WIRE: true
  REPEATER: true
  SHULKER_BOX: true
  SPRUCE_BUTTON: true
  SPRUCE_DOOR: true
  SPRUCE_FENCE_GATE: true
  SPRUCE_TRAPDOOR: true
  STONE_BUTTON: true
  TRAPPED_CHEST: true
  TRIAL_SPAWNER: true
  VAULT: true
  WARPED_BUTTON: true
  WARPED_DOOR: true
  WARPED_FENCE_GATE: true
  WARPED_TRAPDOOR: true
  WAXED_COPPER_DOOR: true
  WAXED_COPPER_TRAPDOOR: true
  WAXED_EXPOSED_COPPER_DOOR: true
  WAXED_EXPOSED_COPPER_TRAPDOOR: true
  WAXED_OXIDIZED_COPPER_DOOR: true
  WAXED_OXIDIZED_COPPER_TRAPDOOR: true
  WAXED_WEATHERED_COPPER_DOOR: true
  WAXED_WEATHERED_COPPER_TRAPDOOR: true
  WEATHERED_COPPER_DOOR: true
  WEATHERED_COPPER_TRAPDOOR: true
  WHITE_CANDLE: true
  WHITE_SHULKER_BOX: true
  YELLOW_CANDLE: true
  YELLOW_SHULKER_BOX: true
disable-harvest-blocks:
  BEE_NEST: true
  BEEHIVE: true
  CAVE_VINES: true
  CAVE_VINES_PLANT: true
  SWEET_BERRY_BUSH: true
disable-change-blocks:
  ACACIA_LOG: true
  ACACIA_WOOD: true
  BAMBOO_BLOCK: true
  BIRCH_LOG: true
  BIRCH_WOOD: true
  CHERRY_LOG: true
  CHERRY_WOOD: true
  CHISELED_COPPER: true
  COARSE_DIRT: true
  COPPER_BLOCK: true
  COPPER_BULB: true
  COPPER_DOOR: true
  COPPER_GRATE: true
  COPPER_TRAPDOOR: true
  CRIMSON_HYPHAE: true
  CRIMSON_STEM: true
  CUT_COPPER: true
  CUT_COPPER_SLAB: true
  CUT_COPPER_STAIRS: true
  DARK_OAK_LOG: true
  DARK_OAK_WOOD: true
  DIRT: true
  DIRT_PATH: true
  EXPOSED_CHISELED_COPPER: true
  EXPOSED_COPPER: true
  EXPOSED_COPPER_BULB: true
  EXPOSED_COPPER_DOOR: true
  EXPOSED_COPPER_GRATE: true
  EXPOSED_COPPER_TRAPDOOR: true
  EXPOSED_CUT_COPPER: true
  EXPOSED_CUT_COPPER_SLAB: true
  EXPOSED_CUT_COPPER_STAIRS: true
  GRASS_BLOCK: true
  JUNGLE_LOG: true
  JUNGLE_WOOD: true
  MANGROVE_LOG: true
  MANGROVE_WOOD: true
  MYCELIUM: true
  OAK_LOG: true
  OAK_WOOD: true
  OXIDIZED_CHISELED_COPPER: true
  OXIDIZED_COPPER: true
  OXIDIZED_COPPER_BULB: true
  OXIDIZED_COPPER_DOOR: true
  OXIDIZED_COPPER_GRATE: true
  OXIDIZED_COPPER_TRAPDOOR: true
  OXIDIZED_CUT_COPPER: true
  OXIDIZED_CUT_COPPER_SLAB: true
  OXIDIZED_CUT_COPPER_STAIRS: true
  PODZOL: true
  PUMPKIN: true
  ROOTED_DIRT: true
  SPRUCE_LOG: true
  SPRUCE_WOOD: true
  TRIAL_SPAWNER: true
  VAULT: true
  WARPED_HYPHAE: true
  WARPED_STEM: true
  WAXED_COPPER_BLOCK: true
  WEATHERED_CHISELED_COPPER: true
  WEATHERED_COPPER: true
  WEATHERED_COPPER_BULB: true
  WEATHERED_COPPER_DOOR: true
  WEATHERED_COPPER_GRATE: true
  WEATHERED_COPPER_TRAPDOOR: true
  WEATHERED_CUT_COPPER: true
  WEATHERED_CUT_COPPER_SLAB: true
  WEATHERED_CUT_COPPER_STAIRS: true
disable-buckets:
  AXOLOTL_BUCKET: true
  BUCKET: true
  COD_BUCKET: true
  LAVA_BUCKET: true
  MILK_BUCKET: true
  POWDER_SNOW_BUCKET: true
  PUFFERFISH_BUCKET: true
  SALMON_BUCKET: true
  TADPOLE_BUCKET: true
  TROPICAL_FISH_BUCKET: true
  WATER_BUCKET: true
disable-beds:
  WHITE_BED: true
  LIGHT_GRAY_BED: true
  GRAY_BED: true
  BLACK_BED: true
  BROWN_BED: true
  RED_BED: true
  ORANGE_BED: true
  YELLOW_BED: true
  LIME_BED: true
  GREEN_BED: true
  CYAN_BED: true
  LIGHT_BLUE_BED: true
  BLUE_BED: true
  PURPLE_BED: true
  MAGENTA_BED: true
  PINK_BED: true
friendly:
  ALLAY: true
  ARMADILLO: true
  ARMOR_STAND: true
  AXOLOTL: true
  BEE: true
  CAMEL: true
  CAT: true
  CHICKEN: true
  COD: true
  COW: true
  DOLPHIN: true
  DONKEY: true
  FOX: true
  FROG: true
  GOAT: true
  HAPPY_GHAST: true
  HORSE: true
  IRON_GOLEM: true
  ITEM_FRAME: true
  LEASH_KNOT: true
  LLAMA: true
  MINECART: true
  MOOSHROOM: true
  MULE: true
  OCELOT: true
  PAINTING: true
  PANDA: true
  PARROT: true
  PIG: true
  PUFFERFISH: true
  RABBIT: true
  SALMON: true
  SHEEP: true
  SKELETON_HORSE: true
  SNIFFER: true
  SNOW_GOLEM: true
  SQUID: true
  STRIDER: true
  TADPOLE: true
  TRADER_LLAMA: true
  TROPICAL_FISH: true
  TURTLE: true
  VILLAGER: true
  WANDERING_TRADER: true
  WOLF: true
  ZOMBIE_HORSE: true
